-- Add the minimal Stripe refund columns required by the admin refund flow.
-- Run this manually, then run:
--   npx prisma db pull
--   npx prisma generate

ALTER TABLE business_order
  ADD COLUMN IF NOT EXISTS STRIPE_CHECKOUT_SESSION_ID VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS STRIPE_PAYMENT_INTENT_ID VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS STRIPE_REFUND_ID VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS STRIPE_REFUND_STATUS VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS STRIPE_REFUNDED_DATETIME DATETIME(0) NULL;
